const choose = (selector) => document.querySelector(selector);
const chooseAll = (selector) => document.querySelectorAll(selector);

export default {
  LOCAL_KEY: 'settingForExercise',
  BOARD_KEY: 'usersRecords',
  elem: {
    header: choose('header'),
    main: choose('main'),
    footer: choose('footer'),
  },
  box: {
    menu: choose('[data-box="menu"]'),
    lang: choose('[data-box="lang"]'),
    app: choose('[data-box="app"]'),
    main: choose('[data-box="main"]'),
    settings: choose('[data-box="settings"]'),
    mode: choose('[data-box="mode"]'),
    exercise: choose('[data-box=exercise]'),
    timer: choose('[data-box="timer"]'),
    board: choose('[data-box="board"]'),
    timerParagraphBox: choose('.timer__clock'),
  },
  lang: {
    en: choose('[data-lang="en"]'),
    ua: choose('[data-lang="ua"]'),
  },
  menu: {
    main: choose('[data-menu="main"]'),
    board: choose('[data-menu="board"]'),
  },
  main: {
    title: choose('[data-mainTitle]'),
    paragraph: choose('[data-mainParagraph]'),
    start: choose('[data-start="yes"]'),
  },
  mode: {
    auto: choose('[data-mode="auto"]'),
    manual: choose('[data-mode="manual"]'),
    challenge: choose('[data-mode="challenge"]'),
  },
  settings: {
    reset: choose('[data-button="reset"]'),
    paragraphOne: choose('[data-paragraph="multiplicand"]'),
    paragraphTwo: choose('[data-paragraph="multiplier"]'),
    multiplicand: {
      round: choose('[data-mode-multiplicand="round"]'),
      random: choose('[data-mode-multiplicand="random"]'),
    },
    multiplicandRandomSub: {
      one: choose('[data-mode-submultiplicand="one"]'),
      two: choose('[data-mode-submultiplicand="two"]'),
    },
    multiplier: {
      round: choose('[data-mode-multiplier="round"]'),
      random: choose('[data-mode-multiplier="random"]'),
    },
    multiplierRandomSub: {
      one: choose('[data-mode-submultiplier="one"]'),
      two: choose('[data-mode-submultiplier="two"]'),
    },
  },
  timer: {
    input: choose('[data-timer="input"]'),
    set: choose('[data-timer="set"]'),
    switch: choose('[data-timer="switch"]'),
    min: choose('[data-timer="mm"]'),
    sec: choose('[data-timer="ss"]'),
  },
  exercise: {
    factorOne: choose('[data-factor="one"]'),
    factorTwo: choose('[data-factor="two"]'),
    product: choose('[data-factor="product"]'),
    next: choose('[data-button="next"]'),
    answer: choose('[data-exercise="answer"]'),
    imgCheck: choose('[data-exercise="check"]'),
    imgCross: choose('[data-exercise="cross"]'),
    imgQuestion: choose('[data-exercise="question"]'),
  },
  board: {
    list: choose('[data-board="list"]'),
    name: choose('[data-board="name"]'),
    score: choose('[data-board="score"]'),
    right: choose('[data-board="right"]'),
    wrong: choose('[data-board="wrong"]'),
    time: choose('[data-board="time"]'),
    reset: choose('[data-board="reset"]'),
  },
  modal: {
    window: choose('[data-modal="modal"]'),
    markup: choose('[data-modal="markUp"]'),
    title: choose('[data-modal="title"]'),
    time: choose('[data-modal="time"]'),
    score: choose('[data-modal="score"]'),
    right: choose('[data-modal="right"]'),
    wrong: choose('[data-modal="wrong"]'),
    button: choose('[data-modal="button"]'),
  },
  tutor: {
    modal: choose('[data-modal="tutorial"]'),
    zero: choose('[data-tutor="0"]'),
    first: choose('[data-tutor="1"]'),
    second: choose('[data-tutor="2"]'),
    third: choose('[data-tutor="3"]'),
    four: choose('[data-tutor="4"]'),
    five: choose('[data-tutor="5"]'),
    six: choose('[data-tutor="6"]'),
    seven: choose('[data-tutor="7"]'),
    eight: choose('[data-tutor="8"]'),
    nine: choose('[data-tutor="9"]'),
    next: choose('[data-tutor="next"]'),
  },
  tutorElems: {
    zeroTitle: choose('.zero__title'),
    zeroTime: choose('.zero__time'),
    firstOff: choose('.first__off'),
    firstOn: choose('.first__on'),
    secondInput: choose('.second__input'),
    thirdSettings: choose('.third__settings'),
    fourMenu: choose('.four__menu'),
    fiveManual: choose('.five__manual'),
    sixChallenge: choose('.six__challenge'),
    sixTime: choose('.six__time'),
    sevenSettings: choose('.seven__settings'),
    eightText: choose('.eight__text'),
  },
  label: {
    multiplicandRound: choose('[data-label-multiplicand="round"]'),
    multiplicandRandom: choose('[data-label-multiplicand="random"]'),
    multiplicandRandomSubOne: choose('[data-label-submultiplicand="one"]'),
    multiplicandRandomSubTwo: choose('[data-label-submultiplicand="two"]'),
    multiplierRound: choose('[data-label-multiplier="round"]'),
    multiplierRandom: choose('[data-label-multiplier="random"]'),
    multiplierRandomSubOne: choose('[data-label-submultiplier="one"]'),
    multiplierRandomSubTwo: choose('[data-label-submultiplier="two"]'),
    timer: choose('[data-label-timer]'),
  },
};
