export default {
  en: {
    title: 'Multiplication Trainer',
    menu: {
      main: 'Simulator',
      board: 'Leaderboard',
    },
    main: {
      title: 'Hi! You are on the multiplication simulator page!',
      paragraph: 'Press the start and train your brains!',
      start: 'Start Exercise',
    },
    mode: {
      auto: 'Auto',
      manual: 'Manual',
      challenge: 'Challenge',
    },
    settings: {
      paragraphOne: 'Multiplicand',
      paragraphTwo: 'Multiplier',
    },
    timer: {
      set: 'Set!',
      switch: 'Enable the timer',
    },
    exercise: {
      next: 'Next!',
    },
    board: {
      name: 'Player',
      score: 'Score',
      right: 'Right',
      wrong: 'Wrong',
      time: 'Time',
      reset: 'Reset',
    },
    tutor: {
      next: 'Next',
    },
    tutorElems: {
      zeroTitle: 'What to do here? <br /> Now you need to set a timer',
      zeroTime: 'Click and set the time',
      firstOff: 'Play with or without timer',
      firstOn: 'Turn on!',
      secondInput: 'Enter the answer and press "Enter" or on the button',
      thirdSettings: 'Here set the difficulty level and choose the game mode',
      fourMenu: 'Switch Between Exercises and Records <Br /> (Challenge Mode)',
      fiveManual: 'Here you can write an example and find out the answer',
      sixChallenge: "Write a reply right away and let's go!",
      sixTime: 'The timer starts automatically',
      sevenSettings: 'The difficulty increases with each correct answer!',
      eightText: 'Go ahead and check your mathematical abilities! ',
    },
    label: {
      multiplicandRound: 'Round',
      multiplicandRandom: 'Random',
      multiplicandRandomSubOne: 'One number',
      multiplicandRandomSubTwo: 'Two numbers',
      multiplierRound: 'Round',
      multiplierRandom: 'Random',
      multiplierRandomSubOne: 'One number',
      multiplierRandomSubTwo: 'Two numbers',
      timer: 'Set ur timer for exercise',
    },
  },
  ua: {
    title: 'Тренажер множення',
    menu: {
      main: 'Тренажер',
      board: 'Таблиця лідерів',
    },
    main: {
      title: 'Привіт! Ти на сторінці симулятора множення!',
      paragraph: 'Натисни "Старт" і тренуй свій мозок!',
      start: 'Розпочати вправу',
    },
    mode: {
      auto: 'Авто',
      manual: 'Вручну',
      challenge: 'Виклик',
    },
    settings: {
      paragraphOne: 'Множник',
      paragraphTwo: 'Множене',
    },
    timer: {
      set: 'Встановити!',
      switch: 'Активувати таймер',
    },
    exercise: {
      next: 'Далі!',
    },
    board: {
      name: 'Гравець',
      score: 'Очки',
      right: 'Вірно',
      wrong: 'Невірно',
      time: 'Час',
      reset: 'Скинути',
    },
    tutor: {
      next: 'Далі',
    },
    tutorElems: {
      zeroTitle: 'Що тут робити?<br />Зараз потрібно встановити таймер',
      zeroTime: 'Клікай та задавай час',
      firstOff: 'Грай з таймером або без',
      firstOn: 'Вмикай!',
      secondInput: 'Вводи відповідь і тисни "Enter" або на кнопку',
      thirdSettings: 'Тут встанови рівень складності та обери режим гри',
      fourMenu: 'Перемикай між вправами та рекордами <br />(режим виклику)',
      fiveManual: 'Тут можна написати приклад і дізнатись відповідь',
      sixChallenge: 'Одразу пиши відповідь і погнали!',
      sixTime: 'Таймер стартує автоматично',
      sevenSettings: 'Складність підвищується з кожною правильною відповіддю!',
      eightText: 'Перевірте свої математичні здібності! Вперед!',
    },
    label: {
      multiplicandRound: 'По колу',
      multiplicandRandom: 'Випадково',
      multiplicandRandomSubOne: 'Одне число',
      multiplicandRandomSubTwo: 'Два числа',
      multiplierRound: 'По колу',
      multiplierRandom: 'Випадково',
      multiplierRandomSubOne: 'Одне число',
      multiplierRandomSubTwo: 'Два числа',
      timer: 'Встанови таймер для вправи',
    },
  },
};
